CRUD/urls.py
from django.conf.urls import url

from . import views

app_name = 'CRUD'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^nuevo$', views.CreatePersona.as_view(), name='new'),
    url(r'^editar/(?P<pk>\d+)$', views.UpdatePersona.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', views.DeletePersona.as_view(), name='delete'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^CRUD/', include('CRUD.urls')),
    url(r'^admin/', admin.site.urls),
]

CRUD/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
# Create your models here.
class Persona(models.Model):
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.name + " " + self.address + " " + self.email

    def getName(self):
        return self.name

    def getAddress(self):
        return self.address

    def getEmail(self):
        return self.email

CRUD/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Persona
from django.views import generic
from django.views.generic.edit import DeleteView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'CRUD/index.html'
    context_object_name = 'latest_persona_list'

    def get_queryset(self):
        return Persona.objects.order_by('name')

class CreatePersona(CreateView):
    model = Persona
    success_url = reverse_lazy('CRUD:index')
    fields = ['name', 'address', 'email']

class DeletePersona(DeleteView):
    model = Persona
    success_url = reverse_lazy('CRUD:index')

class UpdatePersona(UpdateView):
    model = Persona
    success_url = reverse_lazy('CRUD:index')
    fields = ['name', 'address', 'email']

CRUD/templates/CRUD/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>DJANGO SITE</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- NAV BAR -->
    <section>
        <nav class="navbar navbar-inverse">
            <div class= "container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><strong>DJANGO</strong></a>
                </div>
                <p class="navbar-text">DICCIONARIO BASICO DE PERSONAS</p>
            </div>
        </nav>
    </section>
    <br/>
    {% if latest_persona_list %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p class="text-right"> <a href="{% url "CRUD:new" %}" style="color:#080A09;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Agregar registro a la BD</a> </p>
            </div>
        </div>
    </div>
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">REGISTROS EN LA BASE DE DATOS</h3>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <th >NOMBRE</th>
                                    <th >DIRECCION</th>
                                    <th >EMAIL</th>
                                    <th colspan="2"> ACCIONES</th>
                                </tr>
                                {% for persona in latest_persona_list %}
                                    <tr >
                                        <td>{{ persona.getName }}</td>
                                        <td>{{ persona.getAddress }}</td>
                                        <td>{{ persona.getEmail }}</td>
                                        <td><a href="{% url "CRUD:edit" persona.id %}" style="color:#002FFF;"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar</a></td>
                                        <td><a href="{% url "CRUD:delete" persona.id %}" style="color:#FF0000;"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Borrar</a> </td>
                                    </tr>  
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <h2 align="center">No hay registros en la BD, agregue uno para continuar...</h2>
        <p align="center"><a href="{% url "CRUD:new" %}" class="btn btn-primary">AÑADIR PRIMER REGISTRO</a></p>
    {% endif %}  
    
    
    
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

CRUD/templates/CRUD/persona_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>DJANGO SITE</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>
    <!-- NAV BAR -->
    <section>
        <nav class="navbar navbar-inverse">
            <div class= "container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><strong>DJANGO</strong></a>
                </div>
                <p class="navbar-text">DICCIONARIO BASICO DE PERSONAS</p>
            </div>
        </nav>
    </section>
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">CONFIRMACION</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post" class="form-horizontal">{% csrf_token %}
                            <h2 align="center">¿Estás seguro que deseas borrar el registro de:<br/>"{{ object.getName }}"?</h2>
                            <div class="form-actions">
                                <p align="right">
                                    <a href="{% url "CRUD:index" %}" class="btn btn-primary">CANCELAR</a>
                                    <button type="submit" class="btn btn-danger">ELIMINAR</button>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    </body>
</html>

CRUD/templates/CRUD/persona_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>DJANGO SITE</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- NAV BAR -->
    <section>
        <nav class="navbar navbar-inverse">
            <div class= "container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><strong>DJANGO</strong></a>
                </div>
                <p class="navbar-text">DICCIONARIO BASICO DE PERSONAS</p>
            </div>
        </nav>
    </section>
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title" align="center">INGRESE LA INFORMACION</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post" class="form-horizontal">
                            {% csrf_token %}
                            <br/>
                            {% for field in form %}
                            <fieldset class="control-group">
                                <label class="col-sm-4 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                                <div class="col-sm-8 controls">
                                    {{ field }}
                                    <p class="help-text">{{ field.help_text }} </p>
                                </div>
                            </fieldset>
                            {% endfor %}
                            <br/>
                            <div class="form-actions">
                                <p align="right">
                                    <a href="{% url "CRUD:index" %}" class="btn btn-danger">CANCELAR</a>
                                    <button type="submit" class="btn btn-primary">ENVIAR</button>
                                </p>
                            </div>
                        </form>     
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>